stages:
  - test
  - security

variables:
  CHECKOV_VERSION: "latest"

checkov_iac_scan:
  stage: security
  image:
    name: bridgecrew/checkov:${CHECKOV_VERSION}
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - mkdir -p reports
  script:
    - checkov -d ./terraform/remediated --external-checks-dir ./custom_policies/yaml --external-checks-dir ./custom_policies/python --output cli --output junitxml --output-file-path ./reports --hard-fail-on HIGH
  artifacts:
    when: always
    reports:
      junit: reports/results_junitxml.xml
    paths:
      - reports/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
